application: nycsamosa
version: 2
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /.*
  script: main.py
- url: /_ah/mail/.+
  script: main.py
  login: admin  
inbound_services:
- mail

indexes:
- kind: Street
	properties:
	- name: borough
	- name: zipcode